const express = require('express');
const router = express.Router();

const WORKOUTS = [
  {
    id: 1,
    name: 'Classic Push Day',
    description: 'Build a powerful chest, shoulders and triceps with this classic push routine.',
    muscleGroup: 'Chest',
    difficulty: 'Intermediate',
    duration: 60,
    imageEmoji: '🏋️',
    exercises: [
      { name: 'Barbell Bench Press', sets: 4, reps: '6-8', rest: '2 min' },
      { name: 'Incline Dumbbell Press', sets: 3, reps: '10-12', rest: '90 sec' },
      { name: 'Overhead Press', sets: 3, reps: '8-10', rest: '90 sec' },
      { name: 'Lateral Raises', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Tricep Pushdown', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Skull Crushers', sets: 3, reps: '10-12', rest: '60 sec' },
    ],
  },
  {
    id: 2,
    name: 'Back & Biceps Builder',
    description: 'Develop a thick, wide back and strong biceps with this pulling program.',
    muscleGroup: 'Back',
    difficulty: 'Intermediate',
    duration: 65,
    imageEmoji: '💪',
    exercises: [
      { name: 'Deadlift', sets: 4, reps: '4-6', rest: '3 min' },
      { name: 'Pull-ups / Lat Pulldown', sets: 4, reps: '8-10', rest: '2 min' },
      { name: 'Bent-Over Barbell Row', sets: 3, reps: '8-10', rest: '90 sec' },
      { name: 'Seated Cable Row', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Barbell Bicep Curl', sets: 3, reps: '10-12', rest: '60 sec' },
      { name: 'Hammer Curls', sets: 3, reps: '12-15', rest: '60 sec' },
    ],
  },
  {
    id: 3,
    name: 'Leg Day Destroyer',
    description: 'Comprehensive lower body training targeting quads, hamstrings and glutes.',
    muscleGroup: 'Legs',
    difficulty: 'Advanced',
    duration: 75,
    imageEmoji: '🦵',
    exercises: [
      { name: 'Back Squat', sets: 5, reps: '5', rest: '3 min' },
      { name: 'Romanian Deadlift', sets: 4, reps: '8-10', rest: '2 min' },
      { name: 'Leg Press', sets: 3, reps: '12-15', rest: '90 sec' },
      { name: 'Walking Lunges', sets: 3, reps: '10 each leg', rest: '90 sec' },
      { name: 'Leg Curl', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Calf Raises', sets: 4, reps: '15-20', rest: '60 sec' },
    ],
  },
  {
    id: 4,
    name: 'Shoulder Sculpt',
    description: 'Build wide, capped shoulders with this targeted deltoid program.',
    muscleGroup: 'Shoulders',
    difficulty: 'Intermediate',
    duration: 50,
    imageEmoji: '🎯',
    exercises: [
      { name: 'Seated Dumbbell Press', sets: 4, reps: '8-10', rest: '2 min' },
      { name: 'Arnold Press', sets: 3, reps: '10-12', rest: '90 sec' },
      { name: 'Front Raises', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Lateral Raises', sets: 4, reps: '15-20', rest: '60 sec' },
      { name: 'Rear Delt Fly', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Upright Row', sets: 3, reps: '10-12', rest: '60 sec' },
    ],
  },
  {
    id: 5,
    name: 'Arm Blast',
    description: 'Maximize bicep and tricep growth with this dedicated arm workout.',
    muscleGroup: 'Arms',
    difficulty: 'Beginner',
    duration: 45,
    imageEmoji: '💪',
    exercises: [
      { name: 'EZ-Bar Curl', sets: 4, reps: '10-12', rest: '60 sec' },
      { name: 'Incline Dumbbell Curl', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Concentration Curl', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Close-Grip Bench Press', sets: 4, reps: '10-12', rest: '90 sec' },
      { name: 'Overhead Tricep Extension', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Diamond Push-ups', sets: 3, reps: '15-20', rest: '60 sec' },
    ],
  },
  {
    id: 6,
    name: 'Core Crusher',
    description: 'Strengthen your core and reveal your abs with this intensive program.',
    muscleGroup: 'Core',
    difficulty: 'Intermediate',
    duration: 30,
    imageEmoji: '🔥',
    exercises: [
      { name: 'Plank', sets: 3, reps: '60 sec', rest: '30 sec' },
      { name: 'Hanging Leg Raises', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Cable Crunches', sets: 3, reps: '15-20', rest: '60 sec' },
      { name: 'Russian Twists', sets: 3, reps: '20 each side', rest: '45 sec' },
      { name: 'Ab Wheel Rollout', sets: 3, reps: '10-12', rest: '60 sec' },
      { name: 'Side Plank', sets: 3, reps: '45 sec each', rest: '30 sec' },
    ],
  },
  {
    id: 7,
    name: 'Full Body Strength',
    description: 'A balanced full body workout hitting all major muscle groups in one session.',
    muscleGroup: 'Full Body',
    difficulty: 'Beginner',
    duration: 55,
    imageEmoji: '⚡',
    exercises: [
      { name: 'Goblet Squat', sets: 3, reps: '10-12', rest: '90 sec' },
      { name: 'Push-ups', sets: 3, reps: '12-15', rest: '60 sec' },
      { name: 'Dumbbell Row', sets: 3, reps: '10-12', rest: '90 sec' },
      { name: 'Dumbbell Shoulder Press', sets: 3, reps: '10-12', rest: '90 sec' },
      { name: 'Romanian Deadlift', sets: 3, reps: '10-12', rest: '90 sec' },
      { name: 'Plank', sets: 3, reps: '30-45 sec', rest: '30 sec' },
    ],
  },
  {
    id: 8,
    name: 'HIIT Cardio Blast',
    description: 'High-intensity interval training to torch calories and boost endurance.',
    muscleGroup: 'Cardio',
    difficulty: 'Advanced',
    duration: 35,
    imageEmoji: '🏃',
    exercises: [
      { name: 'Burpees', sets: 4, reps: '10', rest: '30 sec' },
      { name: 'Box Jumps', sets: 4, reps: '10', rest: '30 sec' },
      { name: 'Mountain Climbers', sets: 4, reps: '20 each leg', rest: '30 sec' },
      { name: 'Jump Squats', sets: 4, reps: '15', rest: '30 sec' },
      { name: 'High Knees', sets: 4, reps: '30 sec', rest: '30 sec' },
      { name: 'Jump Rope', sets: 4, reps: '60 sec', rest: '30 sec' },
    ],
  },
  {
    id: 9,
    name: 'Beginner Full Body',
    description: 'Perfect starter program for gym beginners. Learn the fundamentals safely.',
    muscleGroup: 'Full Body',
    difficulty: 'Beginner',
    duration: 45,
    imageEmoji: '🌱',
    exercises: [
      { name: 'Bodyweight Squat', sets: 3, reps: '15', rest: '60 sec' },
      { name: 'Push-ups (modified)', sets: 3, reps: '10', rest: '60 sec' },
      { name: 'Assisted Pull-up', sets: 3, reps: '8', rest: '90 sec' },
      { name: 'Dumbbell Lunges', sets: 3, reps: '10 each', rest: '60 sec' },
      { name: 'Dumbbell Curl', sets: 3, reps: '12', rest: '60 sec' },
      { name: 'Plank Hold', sets: 3, reps: '20 sec', rest: '30 sec' },
    ],
  },
  {
    id: 10,
    name: 'Advanced PPL Program',
    description: 'Push-Pull-Legs split for advanced lifters seeking maximum muscle gains.',
    muscleGroup: 'Full Body',
    difficulty: 'Advanced',
    duration: 90,
    imageEmoji: '🏆',
    exercises: [
      { name: 'Squat', sets: 5, reps: '5', rest: '3 min' },
      { name: 'Bench Press', sets: 5, reps: '5', rest: '3 min' },
      { name: 'Barbell Row', sets: 5, reps: '5', rest: '3 min' },
      { name: 'Overhead Press', sets: 3, reps: '8', rest: '2 min' },
      { name: 'Pull-ups', sets: 3, reps: '8-10', rest: '2 min' },
      { name: 'Romanian Deadlift', sets: 3, reps: '10', rest: '2 min' },
    ],
  },
  {
    id: 11,
    name: 'Steady State Cardio',
    description: 'Low-intensity steady state cardio for fat burning and cardiovascular health.',
    muscleGroup: 'Cardio',
    difficulty: 'Beginner',
    duration: 40,
    imageEmoji: '🚴',
    exercises: [
      { name: 'Treadmill Walk/Jog', sets: 1, reps: '20 min', rest: 'N/A' },
      { name: 'Stationary Bike', sets: 1, reps: '15 min', rest: 'N/A' },
      { name: 'Cool Down Stretch', sets: 1, reps: '5 min', rest: 'N/A' },
    ],
  },
  {
    id: 12,
    name: 'Glute & Hamstring Focus',
    description: 'Specifically targets glutes and hamstrings for lower body development.',
    muscleGroup: 'Legs',
    difficulty: 'Intermediate',
    duration: 55,
    imageEmoji: '🍑',
    exercises: [
      { name: 'Hip Thrust', sets: 4, reps: '10-12', rest: '90 sec' },
      { name: 'Sumo Deadlift', sets: 4, reps: '8-10', rest: '2 min' },
      { name: 'Bulgarian Split Squat', sets: 3, reps: '10 each', rest: '90 sec' },
      { name: 'Leg Curl', sets: 4, reps: '12-15', rest: '60 sec' },
      { name: 'Cable Kickback', sets: 3, reps: '15 each', rest: '60 sec' },
      { name: 'Glute Bridge', sets: 3, reps: '20', rest: '45 sec' },
    ],
  },
];

// GET /api/workouts - returns sample workout programs
router.get('/', (req, res) => {
  res.json(WORKOUTS);
});

module.exports = router;
